#!/bin/bash

# Check for configuration existance
if [ ! -d /config ]; then
    echo "You have not mapped /config"
fi

# Copy servers from configuration
if [ -d /config/servers ]; then
    echo "Generating server configurations..."
    cp /config/servers/generate /etc/nginx/servers/generate
    pushd /etc/nginx/servers
    ./generate
    popd
    rm generate
fi

if [ -d /config/certs ]; then
    echo "Copying SSL certificates..."
    cp -Rv /config/certs /etc/nginx/certs
fi

# Check syntax
/usr/sbin/nginx -t
if [ $? -ne 0 ]; then
    echo "Nginx syntax check fail"
    exit 1
fi

# Run Nginx
/usr/sbin/nginx

# Wait for /run/nginx.pid to appear and copy it.
while [ ! -e /run/nginx.pid ]; do
  echo "Waiting for /run/nginx.pid to appear..."
  sleep 1
done
cp /run/nginx.pid /run/watch/nginx

